version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "[bot]"
    open-pull-requests-limit: 1
    target-branch: "development"
    groups:
      fortawesome:
        patterns:
          - "@fortawesome*"
      mantine:
        patterns:
          - "@mantine*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "[workflow]"
    open-pull-requests-limit: 1
    target-branch: "development"