// Badge action
export const UPDATE_BADGE_MOVIES = "UPDATE_BADGE_MOVIES";
export const UPDATE_BADGE_EPISODES = "UPDATE_BADGE_EPISODES";
export const UPDATE_BADGE_PROVIDERS = "UPDATE_BADGE_PROVIDERS";

// System action
export const UPDATE_LANGUAGES_LIST = "UPDATE_LANGUAGES_LIST";
export const UPDATE_SYSTEM_STATUS = "UPDATE_SYSTEM_STATUS";
export const UPDATE_SYSTEM_TASKS = "UPDATE_SYSTEM_TASKS";
export const EXEC_SYSTEM_TASK = "EXEC_SYSTEM_TASK";

// Series action
export const UPDATE_SERIES_LIST = "UPDATE_SERIES_LIST";
export const UPDATE_SERIES_WANTED_LIST = "UPDATE_SERIES_WANTED_LIST";
export const OPEN_SERIES_EDIT_MODAL = "OPEN_SERIES_EDIT_MODAL";
export const CLOSE_SERIES_EDIT_MODAL = "CLOSE_SERIES_EDIT_MODAL";
