// Badge action
export const UPDATE_BADGE_MOVIES = "UPDATE_BADGE_MOVIES";
export const UPDATE_BADGE_EPISODES = "UPDATE_BADGE_EPISODES";
export const UPDATE_BADGE_PROVIDERS = "UPDATE_BADGE_PROVIDERS";

// System action
export const UPDATE_LANGUAGES_LIST = "UPDATE_LANGUAGES_LIST";
export const UPDATE_SYSTEM_STATUS = "UPDATE_SYSTEM_STATUS"

// Series action
export const UPDATE_SERIES_LIST = "UPDATE_SERIES_LIST";
