// Badge action
export const UPDATE_BADGE_MOVIES = "UPDATE_BADGE_MOVIES";
export const UPDATE_BADGE_EPISODES = "UPDATE_BADGE_EPISODES";
export const UPDATE_BADGE_PROVIDERS = "UPDATE_BADGE_PROVIDERS";
