// Web action
export const INIT_WEB_APP = "INIT_WEB_APP";

// Badge action
export const UPDATE_BADGE_ALL = "UPDATE_BADGE_ALL";

// Provider action
export const UPDATE_PROVIDER_LIST = "UPDATE_PROVIDER_LIST";

// System action
export const UPDATE_LANGUAGES_LIST = "UPDATE_LANGUAGES_LIST";
export const UPDATE_SYSTEM_STATUS = "UPDATE_SYSTEM_STATUS";
export const UPDATE_SYSTEM_TASKS = "UPDATE_SYSTEM_TASKS";
export const UPDATE_SYSTEM_LOGS = "UPDATE_SYSTEM_LOGS";
export const UPDATE_SYSTEM_SETTINGS = "UPDATE_SYSTEM_SETTINGS";
export const EXEC_SYSTEM_TASK = "EXEC_SYSTEM_TASK";
export const SET_SYSTEM_SETTINGS = "SET_SYSTEM_SETTINGS";

// Series action
export const UPDATE_SERIES_LIST = "UPDATE_SERIES_LIST";
export const UPDATE_SERIES_WANTED_LIST = "UPDATE_SERIES_WANTED_LIST";
export const UPDATE_SERIES_EPISODE_LIST = "UPDATE_SERIES_EPISODE_LIST";
export const UPDATE_SERIES_HISTORY_LIST = "UPDATE_SERIES_HISTORY_LIST";
export const UPDATE_SERIES_INFO = "UPDATE_SEIRES_INFO";

// Movie action
export const UPDATE_MOVIE_LIST = "UPDATE_MOVIE_LIST";
export const UPDATE_MOVIE_WANTED_LIST = "UPDATE_MOVIE_WANTED_LIST";
export const UPDATE_MOVIE_HISTORY_LIST = "UPDATE_MOVIE_HISTORY_LIST";
export const UPDATE_MOVIE_INFO = "UPDATE_MOVIE_INFO";
