// Badge action
export const UPDATE_BADGE_MOVIES = "UPDATE_BADGE_MOVIES";
export const UPDATE_BADGE_EPISODES = "UPDATE_BADGE_EPISODES";
export const UPDATE_BADGE_PROVIDERS = "UPDATE_BADGE_PROVIDERS";

// System action
export const UPDATE_LANGUAGES_LIST = "UPDATE_LANGUAGES_LIST";
export const UPDATE_SYSTEM_STATUS = "UPDATE_SYSTEM_STATUS";
export const UPDATE_SYSTEM_TASKS = "UPDATE_SYSTEM_TASKS";
export const UPDATE_SYSTEM_PROVIDERS = "UPDATE_SYSTEM_PROVIDERS";
export const EXEC_SYSTEM_TASK = "EXEC_SYSTEM_TASK";

// Series action
export const UPDATE_SERIES_LIST = "UPDATE_SERIES_LIST";
export const UPDATE_SERIES_WANTED_LIST = "UPDATE_SERIES_WANTED_LIST";
export const UPDATE_SERIES_EPISODE_LIST = "UPDATE_SERIES_EPISODE_LIST";
export const UPDATE_SERIES_HISTORY_LIST = "UPDATE_SERIES_HISTORY_LIST";
export const UPDATE_SERIES_INFO = "UPDATE_SEIRES_INFO";

// Movie action
export const UPDATE_MOVIE_LIST = "UPDATE_MOVIE_LIST";
export const UPDATE_MOVIE_WANTED_LIST = "UPDATE_MOVIE_WANTED_LIST";
export const UPDATE_MOVIE_HISTORY_LIST = "UPDATE_MOVIE_HISTORY_LIST";
