"""empty message

Revision ID: cee6a710cb71
Revises: 195144da1f7e
Create Date: 2023-09-20 23:11:15.678439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6a710cb71'
down_revision = '195144da1f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_episodes', schema=None) as batch_op:
        batch_op.alter_column('file_size',
                              existing_type=sa.INTEGER(),
                              type_=sa.BigInteger(),
                              existing_nullable=True,
                              existing_server_default=sa.text('0'))

    with op.batch_alter_table('table_movies', schema=None) as batch_op:
        batch_op.alter_column('file_size',
                              existing_type=sa.INTEGER(),
                              type_=sa.BigInteger(),
                              existing_nullable=True,
                              existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_movies', schema=None) as batch_op:
        batch_op.alter_column('file_size',
                              existing_type=sa.BigInteger(),
                              type_=sa.INTEGER(),
                              existing_nullable=True,
                              existing_server_default=sa.text('0'))

    with op.batch_alter_table('table_episodes', schema=None) as batch_op:
        batch_op.alter_column('file_size',
                              existing_type=sa.BigInteger(),
                              type_=sa.INTEGER(),
                              existing_nullable=True,
                              existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
