"""empty message

Revision ID: cee6a710cb71
Revises: 195144da1f7e
Create Date: 2023-09-20 23:11:15.678439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6a710cb71'
down_revision = '195144da1f7e'
branch_labels = None
depends_on = None

bind = op.get_context().bind


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if bind.engine.name == 'postgresql':
        with op.batch_alter_table('table_episodes') as batch_op:
            batch_op.alter_column('file_size', type_=sa.BigInteger())

        with op.batch_alter_table('table_movies') as batch_op:
            batch_op.alter_column('file_size', type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
