export enum QueryKeys {
  Movies = "movies",
  Episodes = "episodes",
  Series = "series",
  Badges = "badges",
  FileSystem = "file-system",
  System = "system",
  Settings = "settings",
  Subtitles = "subtitles",
  Providers = "providers",
  Languages = "languages",
  LanguagesProfiles = "languages-profiles",
  Blacklist = "blacklist",
  Search = "search",
  Actions = "actions",
  Announcements = "announcements",
  Tasks = "tasks",
  Jobs = "jobs",
  Backups = "backups",
  Logs = "logs",
  Infos = "infos",
  History = "history",
  Wanted = "wanted",
  Range = "range",
  All = "all",
  Plex = "plex",
}
