export enum QueryKeys {
  Movies = "movies",
  Episodes = "episodes",
  Series = "series",
  Badges = "badges",
  System = "system",
  Settings = "settings",
  Providers = "providers",
  Languages = "languages",
  LanguagesProfiles = "languages-profiles",
  Blacklist = "blacklist",
  Search = "search",
  Tasks = "tasks",
  Logs = "logs",
  History = "history",
  Wanted = "wanted",
  Range = "range",
  All = "all",
}
