
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-07T20:35:34-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ae15d825b24b3445112683bbb7b2e4a9d3ecb8f",
 "version": "0.4.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
