
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-05T11:01:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "71ac18ac3949380d99ee5d73b742bf8c4b3568d0",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
