
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-23T21:22:43-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "73968e5c43bee79a363eb7e30c3fab87f99ca7f8",
 "version": "0.4.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
