# coding=utf-8

import logging
import os
import requests
from urllib.parse import urlencode
from retry.api import retry

from app.config import settings


def generate_autopulse_config(decrypted_token=None):
    """
    Generate complete Autopulse YAML configuration for Plex integration.
    Returns YAML string with triggers, targets, and auth configured for Plex.
    """
    try:
        # Get Plex configuration
        server_url = settings.plex.get('server_url', '')
        server_name = settings.plex.get('server_name', '')
        auth_method = settings.plex.get('auth_method', 'apikey')
        
        # Only proceed if OAuth is configured
        if auth_method != 'oauth':
            return None
            
        # Use provided token or decrypt it if not provided
        if not decrypted_token:
            # Get the decrypted token
            key_existed = bool(getattr(settings.plex, 'encryption_key', None))
            if not key_existed:
                logging.warning("BAZARR no encryption key available for Autopulse config")
                return None
                
            encrypted_token = settings.plex.get('token')
            if not encrypted_token:
                logging.warning("BAZARR no encrypted token available for Autopulse config")
                return None
            
            # Decrypt the token
            try:
                from bazarr.api.plex.security import get_or_create_encryption_key, TokenManager
                key = get_or_create_encryption_key(settings.plex, 'encryption_key')
                token_manager = TokenManager(key)
                decrypted_token = token_manager.decrypt(encrypted_token)
            except Exception as e:
                logging.error(f"BAZARR token decryption failed: {e}")
                return None
        
        if not decrypted_token or not server_url:
            logging.warning("BAZARR missing required Plex configuration")
            return None
        
        # Detect path rewriting needs
        rewrite_config = _detect_path_rewrite()
        
        # Generate YAML configuration with path rewriting if detected
        yaml_config = f"""# Autopulse Configuration - Generated by Bazarr

[app]
database_url = "sqlite://data/autopulse.db"
log_level = "info"

[triggers.bazarr_manual]
type = "manual"{rewrite_config['trigger_section']}

[targets.bazarr_plex]
type = "plex"
url = "{server_url}"
token = "{decrypted_token}"
refresh = true  # Essential for subtitle detection
analyze = false # Optional, can be slow{rewrite_config['target_section']}

# Usage: Bazarr will call GET http://autopulse:2875/triggers/manual?path=/parent/directory
"""
        
        logging.info(f"BAZARR generated Autopulse config for server: {server_name}")
        return {
            'config_yaml': yaml_config,
            'server_name': server_name,
            'rewrite_detected': rewrite_config['detected'],
            'rewrite_suggestion': rewrite_config['suggestion']
        }
            
    except Exception as e:
        logging.error(f"BAZARR error generating Autopulse config: {str(e)}")
        return None


def call_external_webhook(subtitle_path, media_path, language, media_type):
    """
    Call external webhook after subtitle download.
    Supports generic webhooks and Autopulse integration.
    """
    # Check if external webhook is enabled
    if not settings.general.use_external_webhook:
        return

    try:
        # Use parent directory instead of specific file for better grouping
        parent_dir = os.path.dirname(media_path)
        
        # Get webhook configuration
        webhook_url = _get_webhook_url()
        auth = _get_webhook_auth()
        
        if not webhook_url:
            logging.debug("BAZARR external webhook not configured, skipping")
            return

        # Prepare query parameters
        params = {'path': parent_dir}
        full_url = f"{webhook_url}?{urlencode(params)}"
        
        headers = {'User-Agent': 'Bazarr'}
        
        logging.debug(f"BAZARR calling external webhook: {webhook_url} for path: {parent_dir}")
        
        # Make the webhook call with retry for network issues
        response = _make_webhook_request(full_url, auth, headers)
        
        if response.status_code == 200:
            logging.info(f"BAZARR external webhook successful for {parent_dir}")
        else:
            logging.warning(f"BAZARR external webhook failed with status {response.status_code} for {parent_dir}")
            
    except requests.exceptions.RequestException as e:
        logging.error(f"BAZARR external webhook failed for {media_path}: {str(e)}")
    except Exception as e:
        logging.error(f"BAZARR unexpected error calling external webhook for {media_path}: {str(e)}")


@retry(exceptions=(requests.exceptions.RequestException,), tries=3, delay=1, backoff=2, jitter=(0, 1))
def _make_webhook_request(url, auth, headers):
    """Make webhook request with retry logic for network issues."""
    return requests.get(
        url,
        auth=auth,
        headers=headers,
        timeout=30,
        verify=True
    )


def test_external_webhook_connection():
    """
    Test connection to external webhook.
    Returns (success: bool, message: str)
    """
    try:
        webhook_url = _get_webhook_url()
        auth = _get_webhook_auth()
        
        logging.debug(f"BAZARR webhook test - URL: {webhook_url}")
        logging.debug(f"BAZARR webhook test - Auth: {auth is not None}")
        
        if not webhook_url:
            logging.debug("BAZARR webhook test - No URL configured")
            return False, "External webhook not configured"

        # Test with stats endpoint if it looks like Autopulse, otherwise test the main URL
        test_url = webhook_url
        if '/triggers/manual' in webhook_url:
            # For Autopulse, test the stats endpoint instead
            base_url = webhook_url.replace('/triggers/manual', '')
            test_url = f"{base_url}/stats"
        
        headers = {'User-Agent': 'Bazarr'}
        
        logging.debug(f"BAZARR testing external webhook: {test_url}")
        
        response = requests.get(
            test_url,
            auth=auth,
            headers=headers,
            timeout=10,
            verify=True
        )
        
        if response.status_code == 200:
            return True, "External webhook connection successful"
        else:
            return False, f"External webhook connection failed with status {response.status_code}"
            
    except requests.exceptions.RequestException as e:
        return False, f"External webhook connection failed: {str(e)}"
    except Exception as e:
        return False, f"External webhook connection error: {str(e)}"


def _get_webhook_url():
    """Get the webhook URL from external webhook configuration."""
    if settings.general.use_external_webhook:
        webhook_url = settings.general.external_webhook_url.strip()
        if webhook_url:
            # Basic URL validation
            if not webhook_url.startswith(('http://', 'https://')):
                logging.warning(f"BAZARR invalid webhook URL format: {webhook_url} (must start with http:// or https://)")
                return None
            return webhook_url
    
    return None


def _get_webhook_auth():
    """Get authentication for the external webhook."""
    if settings.general.use_external_webhook:
        username = settings.general.external_webhook_username.strip()
        password = settings.general.external_webhook_password.strip()
        
        if username and password:
            return (username, password)
    
    return None


def _detect_path_rewrite():
    """Detect if path rewriting is needed between Bazarr and Plex."""
    try:
        # Get typical Bazarr paths
        movie_path = settings.general.get('movie_path', '')
        series_path = settings.general.get('series_path', '')
        
        # Get Plex library paths if available
        plex_movie_path = settings.plex.get('movie_library', '')
        plex_series_path = settings.plex.get('series_library', '')
        
        # Common path patterns that might need rewriting
        common_rewrites = [
            ('/mnt/media', '/media'),
            ('/host/media', '/plex/media'),
            ('/downloads', '/media'),
            ('/data', '/media'),
            ('/bazarr', '/plex'),
            ('/app/media', '/media'),
        ]
        
        detected = False
        suggestion = ""
        trigger_section = ""
        target_section = ""
        
        # Simple detection: if movie/series paths contain common patterns
        for bazarr_pattern, plex_pattern in common_rewrites:
            if movie_path and bazarr_pattern in movie_path:
                detected = True
                suggestion = f"Detected path pattern '{bazarr_pattern}' in Bazarr settings. Path rewriting configured automatically."
                trigger_section = f"""
rewrite.from = "{bazarr_pattern}"
rewrite.to = "{plex_pattern}" """
                target_section = f"""
rewrite.from = "{plex_pattern}"
rewrite.to = "{bazarr_pattern}" """
                break
        
        return {
            'detected': detected,
            'suggestion': suggestion,
            'trigger_section': trigger_section,
            'target_section': target_section
        }
        
    except Exception as e:
        logging.debug(f"BAZARR path rewrite detection failed: {e}")
        return {
            'detected': False,
            'suggestion': "",
            'trigger_section': "",
            'target_section': ""
        }
