name: Schedule Trigger

on:
  schedule:
    - cron: '0 1 * * *'
      timezone: "America/Toronto"
  workflow_dispatch:

jobs:
  Release-Nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        uses: benc-uk/workflow-dispatch@v1.3.2
        with:
          workflow: "release_beta_to_dev"
          token: ${{ secrets.WF_GITHUB_TOKEN }}
          ref: "refs/heads/development"
